name: Build and Deploy Docusaurus to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3.8.1
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install 
    
    - name: Build Docusaurus
      run: |
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

    - name: Extraer y establecer el nombre del dueño y del repositorio en variables de entorno
      run: |
        echo "REPO_OWNER=$(echo ${{ github.repository }} | cut -d '/' -f 1)" >> $GITHUB_ENV
        echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV
    - name: Mostrar el nombre del dueño y del repositorio
      run: |
        echo "El nombre del dueño del repositorio es: $REPO_OWNER"
        echo "El nombre del repositorio es: $REPO_NAME"

